language: node_js
node_js:
  - 4
  - 6
  - 7
before_install:
  # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
cache:
  directories:
  - $HOME/.yarn-cache
install:
  - yarn install
script:
  - yarn test -- --coverage
  - cat coverage/lcov.info | ./node_modules/.bin/coveralls
